apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tlm.fullname" . }}-model-registry
  labels:
    {{- include "tlm.labels" . | nindent 4 }}
data:
  models.json: |
    {{ toYaml .Values.chat_backend.models | nindent 4 }}
